# FIRST LINE/ROW: Info & Status
# First param â”€â”Œ
[username]
format = " [â•­â”€$user]($style)@"
show_always = true
style_root = "bold red"
style_user = "bold red"

# Second param
[hostname]
format = "[$hostname]($style) in "
ssh_only = false
style = "bold dimmed red"
trim_at = "-"

# Third param
[directory]
style = "bold purple"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "

# Fourth param
[sudo]
style = "bold yellow"
symbol = "î¯‡ "

# Version info
[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
deleted = "x"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
style = "bold white"

# Last param in the first line/row
[cmd_duration]
format = "took [$duration]($style)"
min_time = 1
style = "bold blue"

# SECOND LINE/ROW: Prompt
# Battery status
[battery]
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"
full_symbol = "ï•¸"

[[battery.display]]
style = "bold red"
threshold = 15

[[battery.display]]
style = "bold yellow"
threshold = 50

[[battery.display]]
style = "bold green"
threshold = 80

# Time display
[time]
format = " ğŸ•™ $time($style)\n"
style = "bright-white"
time_format = "%T"

# Character display
[character]
error_symbol = " [Ã—](bold red)"
success_symbol = " [â•°â”€Î»](bold green)"

# Symbols
[status]
format = '[

\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]

]($style)'
map_symbol = true
pipestatus = true
symbol = "ğŸ”´"

# AWS
[aws]
symbol = "îŒ½ "
style = "bold blue"

# Conda
[conda]
symbol = "î¨ "
style = "bold green"

# Dart
[dart]
symbol = "î˜ "
style = "bold cyan"

# Docker context
[docker_context]
symbol = "ïŒˆ "
style = "bold blue"

# Elixir
[elixir]
symbol = "î‰µ "
style = "bold magenta"

# Elm
[elm]
symbol = "î˜¬ "
style = "bold green"

# Git branch
[git_branch]
symbol = "ï˜ "
style = "bold red"

# Go
[golang]
symbol = "î˜§ "
style = "bold cyan"

# Hg branch
[hg_branch]
symbol = "ï˜ "
style = "bold red"

# Java
[java]
symbol = "î‰– "
style = "bold purple"

# Julia
[julia]
symbol = "î˜¤ "
style = "bold green"

# Nim
[nim]
symbol = "î™· "
style = "bold yellow"

# Nix shell
[nix_shell]
symbol = "ï‹œ "
style = "bold blue"

# Node.js
[nodejs]
symbol = "î‰ "
style = "bold green"

# Package
[package]
symbol = "ï£– "
style = "bold yellow"

# Perl
[perl]
symbol = "î© "
style = "bold blue"

# PHP
[php]
symbol = "î˜ˆ "
style = "bold blue"

# Python
[python]
symbol = "î˜† "
style = "bold yellow"

# Ruby
[ruby]
symbol = "îˆ¾ "
style = "bold red"

# Rust
[rust]
symbol = "î¨ "
style = "bold orange"

# Swift
[swift]
symbol = "ï¯£ "
style = "bold red"

